package it.sian.cooperazione.wspdd.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-03-14T13:40:18.770+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "wsRegVino", 
                  wsdlLocation = "wsRegVino.wsdl",
                  targetNamespace = "http://cooperazione.sian.it/wspdd/services") 
public class WsRegVino extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cooperazione.sian.it/wspdd/services", "wsRegVino");
    public final static QName WsRegVino = new QName("http://cooperazione.sian.it/wspdd/services", "wsRegVino");
    static {
        URL url = WsRegVino.class.getResource("wsRegVino.wsdl");
        if (url == null) {
            url = WsRegVino.class.getClassLoader().getResource("wsRegVino.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(WsRegVino.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wsRegVino.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public WsRegVino(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsRegVino(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsRegVino() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRegVino(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRegVino(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRegVino(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WsRegVinoInterService
     */
    @WebEndpoint(name = "wsRegVino")
    public WsRegVinoInterService getWsRegVino() {
        return super.getPort(WsRegVino, WsRegVinoInterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsRegVinoInterService
     */
    @WebEndpoint(name = "wsRegVino")
    public WsRegVinoInterService getWsRegVino(WebServiceFeature... features) {
        return super.getPort(WsRegVino, WsRegVinoInterService.class, features);
    }

}
