package it.sian.cooperazione.wspdd.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-03-14T13:40:18.728+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://cooperazione.sian.it/wspdd/services", name = "wsRegVinoInterService")
@XmlSeeAlso({it.sian.cooperazione.schema.wsmrga.ObjectFactory.class, it.sian.cooperazione.schema.soapautenticazione.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsRegVinoInterService {

    @WebMethod(operationName = "GetVasiSiRPV")
    @WebResult(name = "GetVasiSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetVasiSiRPVOutput getVasiSiRPV(
        @WebParam(partName = "body", name = "GetVasiSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetVasiSiRPVInput body
    );

    @WebMethod(operationName = "GetCancSoggSiRPV")
    @WebResult(name = "GetCancSoggSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetCancSoggSiRPVOutput getCancSoggSiRPV(
        @WebParam(partName = "body", name = "GetCancSoggSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetCancSoggSiRPVInput body
    );

    @WebMethod(operationName = "GetProdSiRPV")
    @WebResult(name = "GetProdSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetProdSiRPVOutput getProdSiRPV(
        @WebParam(partName = "body", name = "GetProdSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetProdSiRPVInput body
    );

    @WebMethod(operationName = "GetSoggSiRPV")
    @WebResult(name = "GetSoggSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetSoggSiRPVOutput getSoggSiRPV(
        @WebParam(partName = "body", name = "GetSoggSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetSoggSiRPVInput body
    );

    @WebMethod(operationName = "VisProdSiRPV")
    @WebResult(name = "VisProdSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.VisProdSiRPVOutput visProdSiRPV(
        @WebParam(partName = "body", name = "VisProdSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.VisProdSiRPVInput body
    );

    @WebMethod(operationName = "GetOperSiRPV")
    @WebResult(name = "GetOperSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetOperSiRPVOutput getOperSiRPV(
        @WebParam(partName = "body", name = "GetOperSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetOperSiRPVInput body
    );

    @WebMethod(operationName = "VisSoggSiRPV")
    @WebResult(name = "VisSoggSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.VisSoggSiRPVOutput visSoggSiRPV(
        @WebParam(partName = "body", name = "VisSoggSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.VisSoggSiRPVInput body
    );

    @WebMethod(operationName = "VisVigneSiRPV")
    @WebResult(name = "VisVigneSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.VisVigneSiRPVOutput visVigneSiRPV(
        @WebParam(partName = "body", name = "VisVigneSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.VisVigneSiRPVInput body
    );

    @WebMethod(operationName = "VisOperSiRPV")
    @WebResult(name = "VisOperSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.VisOperSiRPVOutput visOperSiRPV(
        @WebParam(partName = "body", name = "VisOperSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.VisOperSiRPVInput body
    );

    @WebMethod(operationName = "GetCancVasiSiRPV")
    @WebResult(name = "GetCancVasiSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetCancVasiSiRPVOutput getCancVasiSiRPV(
        @WebParam(partName = "body", name = "GetCancVasiSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetCancVasiSiRPVInput body
    );

    @WebMethod(operationName = "GetCancVigneSiRPV")
    @WebResult(name = "GetCancVigneSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetCancVigneSiRPVOutput getCancVigneSiRPV(
        @WebParam(partName = "body", name = "GetCancVigneSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetCancVigneSiRPVInput body
    );

    @WebMethod(operationName = "GetCancProdSiRPV")
    @WebResult(name = "GetCancProdSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetCancProdSiRPVOutput getCancProdSiRPV(
        @WebParam(partName = "body", name = "GetCancProdSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetCancProdSiRPVInput body
    );

    @WebMethod(operationName = "GetVigneSiRPV")
    @WebResult(name = "GetVigneSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetVigneSiRPVOutput getVigneSiRPV(
        @WebParam(partName = "body", name = "GetVigneSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetVigneSiRPVInput body
    );

    @WebMethod(operationName = "VisGiacSiRPV")
    @WebResult(name = "VisGiacSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.VisGiacSiRPVOutput visGiacSiRPV(
        @WebParam(partName = "body", name = "VisGiacSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.VisGiacSiRPVInput body
    );

    @WebMethod(operationName = "GetCancAzieSiRPV")
    @WebResult(name = "GetCancAzieSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetCancAzieSiRPVOutput getCancAzieSiRPV(
        @WebParam(partName = "body", name = "GetCancAzieSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetCancAzieSiRPVInput body
    );

    @WebMethod(operationName = "GetCancOperSiRPV")
    @WebResult(name = "GetCancOperSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.GetCancOperSiRPVOutput getCancOperSiRPV(
        @WebParam(partName = "body", name = "GetCancOperSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.GetCancOperSiRPVInput body
    );

    @WebMethod(operationName = "VisVasiSiRPV")
    @WebResult(name = "VisVasiSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.VisVasiSiRPVOutput visVasiSiRPV(
        @WebParam(partName = "body", name = "VisVasiSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.VisVasiSiRPVInput body
    );
}
