package it.sian.cooperazione.wspdd.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-20T08:54:28.973+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://cooperazione.sian.it/wspdd/services", name = "wsRegVinoAsyncInterService")
@XmlSeeAlso({it.sian.cooperazione.schema.wsmrga.ObjectFactory.class, it.sian.cooperazione.schema.soapautenticazione.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsRegVinoAsyncInterService {

    @WebMethod(operationName = "VasiSiRPV")
    @WebResult(name = "VasiSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.VasiSiRPVOutput vasiSiRPV(
        @WebParam(partName = "body", name = "VasiSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.VasiSiRPVInput body
    );

    @WebMethod(operationName = "CancOperSiRPV")
    @WebResult(name = "CancOperSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.CancOperSiRPVOutput cancOperSiRPV(
        @WebParam(partName = "body", name = "CancOperSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.CancOperSiRPVInput body
    );

    @WebMethod(operationName = "CancVasiSiRPV")
    @WebResult(name = "CancVasiSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.CancVasiSiRPVOutput cancVasiSiRPV(
        @WebParam(partName = "body", name = "CancVasiSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.CancVasiSiRPVInput body
    );

    @WebMethod(operationName = "CancVigneSiRPV")
    @WebResult(name = "CancVigneSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.CancVigneSiRPVOutput cancVigneSiRPV(
        @WebParam(partName = "body", name = "CancVigneSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.CancVigneSiRPVInput body
    );

    @WebMethod(operationName = "SoggSiRPV")
    @WebResult(name = "SoggSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.SoggSiRPVOutput soggSiRPV(
        @WebParam(partName = "body", name = "SoggSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.SoggSiRPVInput body
    );

    @WebMethod(operationName = "CancSoggSiRPV")
    @WebResult(name = "CancSoggSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.CancSoggSiRPVOutput cancSoggSiRPV(
        @WebParam(partName = "body", name = "CancSoggSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.CancSoggSiRPVInput body
    );

    @WebMethod(operationName = "VigneSiRPV")
    @WebResult(name = "VigneSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.VigneSiRPVOutput vigneSiRPV(
        @WebParam(partName = "body", name = "VigneSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.VigneSiRPVInput body
    );

    @WebMethod(operationName = "OperSiRPV")
    @WebResult(name = "OperSiRPVOutput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/", partName = "body")
    public it.sian.cooperazione.schema.wsmrga.OperSiRPVOutput operSiRPV(
        @WebParam(partName = "body", name = "OperSiRPVInput", targetNamespace = "http://cooperazione.sian.it/schema/wsmrga/")
        it.sian.cooperazione.schema.wsmrga.OperSiRPVInput body
    );
}
